api/auth/preAuth/facebook.js, api/auth/preAuth/github.js, api/auth/preAuth/google.js
Updated Logging to and some scripts to avoid some unwanted posts
=> Initialize node

api/auth/authModel.js, api/private/answers/answers.js, api/private/answers/answersModel.js, api/private/profile/profile.js, api/private/profile/profileModle.js
Fixes # (issue)
Please delete options that are not relevant.
=> Testing Camel Case conversion

data/migrations/20200224145958_admin.js, data/migrations/20200224151645_app.js
created tables for admin, users, and teams
=> Making migration tables

api/server.js, data/seeds/02-users.js, users/users-model.js, users/users-router.js
getUserProfiles: grabs all users in database 
getUserProfileById: grabs a specific user profile by ID
addUser: adds a user to the database
=> set up 3 user routes

users/users-model.js, users/users-router.js
PUT request is giving me issues. It's reading the ID that I am passing in as a column and saying that the 'column {id} does not exist'.
=> added DELETE route for users; PUT request not working

api/server.js, data/migrations/20200224151645_app.js, data/seeds/01-teams.js, teams/teams-model.js, teams/teams-router.js
added getAllTeams, getTeamById, addTeam, deleteTeam db function and routes
=> Teams model

api/server.js, auth/auth-router.js, auth/restricted-middleware.js, config/secrets.js, package-lock.json, package.json, teams/teams-model.js, teams/teams-router.js, users/users-model.js
Login and Registration functionality for user is working. Fixed PUT request for user and added PUT request for teams.
=> Login & registration

auth/auth-router.js
added code to registration to be able to receive a token when signing up.
=> receiving token on registration now

admin/admin-model.js, admin/admin-router.js, api/server.js
successfully able to login admin and receive a token. Haven't added middleware for user or admin.
=> added admin model and router

README.md
added PUT routes and admin login
=> updated routes

admin/admin-model.js, admin/admin-router.js, data/db-config.js
fixed admin bug where any password was logging in
=> Fixing admin bug

data/seeds/02-users.js
fixed seeding issue; new users should populate now.
=> Fixing seed issue

teams/teams-model.js
- updated add team helper to return an array of objects instead of object of single added team
=> Add team helper

data/seeds/01-teams.js, users/users-model.js, users/users-router.js
- modified getUserProfiles db helper to include the name of the team user is on
=> Get user team name

data/migrations/20200224151645_app.js, users/users-model.js
- user is no longer being deleted when their team is
=> Delete team bug fix

api/server.js, data/migrations/20200224151645_app.js, data/seeds/02-users.js, metrics/metrics-model.js, metrics/metrics-router.js, users/users-model.js, users/users-router.js
Changed seed data from first_name and last_name to only full_name, added metrics to  users schema table
=> Shawn patel monday

data/migrations/20200224151645_app.js, data/seeds/02-users.js, users/users-model.js, users/users-router.js
=> rereverted back to full_name

data/migrations/20200224151645_app.js, users/users-model.js
=>  fixed water bug

api/server.js, package.json, yarn.lock
current bug: only resets when set to every second
=> added daily_points/metrics reset at 4am

data/seeds/01-teams.js
Hard coded seed data was causing breaks, deleted team points seed data in order to solve this.
=> deleted team points seed data

README.md
Changed Read Me instructions for setting up postgres
=> Fixed Read Me
